# Generated by Django 3.2.5 on 2021-07-08 15:51

from django.db import migrations, models
import django.db.models.deletion
import staj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=50, primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=staj.models.Student.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('status', models.BooleanField(default='False')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staj.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staj.student')),
            ],
        ),
    ]
